### PR TITLE
fix: update GrabOp classification for GNOME 44

### LINKED ISSUE #1615: Cannot Manage Tiling With Mouse on GNOME 44
**(1) Issue/Bug Description:**

Unable to manage tiling with mouse on GNOME 44. When I hit super to grab a window I can "move" it on screen, but when I let go it just goes back into it's original position. This also means I'm unable to stack windows using my mouse.

**(2) Steps to reproduce (if you know):**

- Press Super
- Grab Window 
- Move window in an attempt to re-arrange the tiling or stack on top of another window 

**(3) Expected behavior:**

It should let me move that window to another place on the screen or stack that window on top of another.

**(4) Distribution (run `cat /etc/os-release`):**
 
```
   cat /etc/os-release 
NAME="Fedora Linux"
VERSION="38 (Workstation Edition)"
ID=fedora
VERSION_ID=38
VERSION_CODENAME=""
PLATFORM_ID="platform:f38"
PRETTY_NAME="Fedora Linux 38 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:38"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f38/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=38
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=38
SUPPORT_END=2024-05-14
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

**(5) Gnome Shell version:**

GNOME 44

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

a3a1b7bb832838fec2ea875954d33443fc680912

**(7) Where was Pop Shell installed from:**

Git

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**

3440x1440 (Horizontal) (Primary), 1080x1920 (Vertical, Secondary)

**(9) Other Installed/Enabled Extensions:**

Installed: 
- Blur my Shell (Disabled)
- Burn My Windows (Disabled)
- GSConnect (Disabled)
- Unite (Enabled)
- User Themes (Disabled)
- AppIndicator and KStatusNotifierItem Support (Disabled)
- Applications Menu (Disabled)
- Background Logo (Disabled)
- GameMode (Disabled)
- Launch new Instance (Disabled)
- Places Status Indicator (Enabled)
- Window List (Disabled)

**(10) Other Notes:**

### PR DESCRIPTION
**Pull request by mooey5775**
Fixes #1615, which is broken due to updates in Clutter's Grab handling behavior in GNOME/Mutter 44. This is described in this merge request (https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2683), and specifically caused by this commit (https://gitlab.gnome.org/GNOME/mutter/-/commit/12773cf8e2954082f346dee300af624b25baf23c)

More concretely, a new `META_GRAB_OP_WINDOW_FLAG_UNCONSTRAINED` flag is added, which should be ignored when determining if a grab op is a move op or not. Unfortunately, this flag is not exposed publicly, and is not backwards compatible with prior versions of GNOME.

The most principled way to fix this is to use these functions in mutter's `display.c` (https://gitlab.gnome.org/GNOME/mutter/-/blob/main/src/core/display.c#L1186), but these are also not public. I've reimplemented here in JS, with some more bit operations to recover the flags that are used. This may not be the most maintainable way to do this, am open to comments.

This works on Fedora 38 (GNOME 44) and Fedora 37 (GNOME 43), although I haven't tested anything older.

[f38_postcommit.webm](https://user-images.githubusercontent.com/7400724/233483438-d619efb6-57db-47dd-a559-e60e794c0bdf.webm)
[f37_postcommit.webm](https://user-images.githubusercontent.com/7400724/233483932-c129f4e1-e857-4348-921d-63d818854739.webm)

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -1411,7 +1411,7 @@ export class Ext extends Ecs.System<ExtEvent> {
 
                 /** Display an overlay indicating where the window will be placed if dropped */
 
-                if (overview.visible || !win || op !== 1) return
+                if (overview.visible || !win || is_keyboard_op(op) || is_resize_op(op)) return
```
Comment (mooey5775) [inline src/extension.ts:1414]: I've tried to replicate the semantics of the earlier code, but it's unclear to me what the condition here is. It doesn't seem to hurt to display overlays if we're doing a keyboard move op, but the previous code doesn't.

**Comment by mooey5775** [comment]
@mmstick bump on this if you have the chance - sorry for the noise

**Comment by n3m0-22** [comment]
@mooey5775 Going over the steps listed in https://github.com/pop-os/shell/issues/1615 I have been unable to reproduce the issue this is meant to solve. I am able to move, stack, and un-stack windows using both the mouse and keyboard without this PR. Are you running Fedora?

**Comment by mmstick** [comment]
@n3m0-22 Yes they're on Fedora 38 with GNOME 44. As long as this doesn't cause regression in Pop with GNOME 42, then I'm fine with merging it.

**Review by n3m0-22 — APPROVED** [review]
Tested with Pop 22.04 on lemp11 and gaze15. All regression testing passed.

[pop-shell-1618-testing.txt](https://github.com/pop-os/shell/files/11346291/pop-shell-1618-testing.txt)

**Review by mmstick — APPROVED** [review]

**Comment by mooey5775** [comment]
Thanks!

For clarity, this problem only happens on GNOME 44 if windows are moved with the window action key (usually `Super + [mouse drag]`. Moving windows by dragging their titlebars would work either before or after this PR.

**Comment by flokli** [comment]
Confirmed this fixes the issue for me. Thanks!
