### PR TITLE
fix(tiling): support resizing/moving windows with the mouse in GNOME 40

### LINKED ISSUE #932: Unable to resize or move window with mouse on Arch Gnome40.
**(1) Issue/Bug Description:**
I can't resize or move the window by dragging it with my mouse.

**(2) Steps to reproduce (if you know):**
Try to resize or move the window with my mouse.

**(3) Expected behavior:**
It resizes or moves the window.

**(4) Distribution (run `cat /etc/os-release`):**
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

**(5) Gnome Shell version:**
40.0.0

**(6) Pop Shell version (run `apt policy pop-shell` or provide the latest commit if building locally):**

```
Name            : gnome-shell-extension-pop-shell-git
Version         : r677.163d207-1
Description     : Pop Shell - Tiling window management in Gnome (WIP)
Architecture    : any
URL             : https://github.com/pop-os/shell
Licenses        : GPLv3
Groups          : None
Provides        : None
Depends On      : gnome-shell  pop-shell-shortcuts-git
Optional Deps   : gnome-shell-extensions: native-window extension for improved window
                  placement [installed]
Required By     : None
Optional For    : None
Conflicts With  : gnome-shell-extension-pop-shell
Replaces        : None
Installed Size  : 1049.04 KiB
Packager        : Unknown Packager
Build Date      : Fri Apr 9 16:46:46 2021
Install Date    : Fri Apr 9 16:46:53 2021
Install Reason  : Explicitly installed
Install Script  : Yes
Validated By    : None
```

**(7) Where was Pop Shell installed from:**
AUR

**(8) Monitor Setup (2 x 1080p, 4K, Primary(Horizontal), Secondary(Vertical), etc):**
1 x 1080p

**(9) Other Installed/Enabled Extensions:**
cpufreq, freon, gamemode, gsconnect, sound-output-device-chooser, appindicator

**(10) Other Notes:**

### PR DESCRIPTION
**Pull request by laurentlbm**
Fixes #932.

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -1789,14 +1789,24 @@ export class Ext extends Ecs.System<ExtEvent> {
             this.register({ tag: 3, window });
         });
 
-        this.connect(display, 'grab-op-begin', (_, _display, win, op) => {
-            this.on_grab_start(win, op);
-        });
+        if (GNOME_VERSION?.startsWith("3.")) {
+            // GNOME 40 removed the first argument of the callback
```
Comment (rengare) [inline src/extension.ts:1793]: this comment should go to else statement

**Review by rengare — DISMISSED** [review]

File: src/extension.ts (hunk 1 above)
Comment (laurentlbm) [reply src/extension.ts]: Done

**Review by mmstick — APPROVED** [review]

**Review by jacobgkau — APPROVED** [review]
Pop!_OS regression testing passed:
[shell-pr1115-hirsute.txt](https://github.com/pop-os/shell/files/6918341/shell-pr1115-hirsute.txt)
[shell-pr1115-focal.txt](https://github.com/pop-os/shell/files/6918519/shell-pr1115-focal.txt)

Confirmed this gets resizing/moving with the mouse working on Fedora 34 with GNOME 40.
