### PR TITLE
Fixed interaction with custom shell themes

### LINKED ISSUE #230: Pop-Shell disrupts theme use
**Distribution (run `cat /etc/os-release`):**

NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.manjaro.org/"
SUPPORT_URL="https://www.manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux

 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
commit:
16b4c33a8542969f19471b13b90764575a45ccf9

**Issue/Bug Description:**
it appears that while using a non-default theme, this disrupts the look of my current theme to be a mix of the default theme (Adwaita) and my theme of choice, Orchis (https://github.com/vinceliuice/Orchis-theme)

**Steps to reproduce (if you know):**
Launch with non default theme, can be fixed if theme is disabled then re-enabled or if the system is locked and then logged back into.

**Expected behavior:**
No effect on the theme.

### LINKED ISSUE #231: Pop Shell does not respect shell theme choice
**Distribution (run `cat /etc/os-release`):**
 NAME=Fedora
VERSION="32 (Workstation Edition)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

 
 
**Related Application and/or Package Version (run `apt policy pop-shell` or provide the latest commit if building locally):**
[commit](https://github.com/pop-os/shell/commit/16b4c33a8542969f19471b13b90764575a45ccf9)

**Issue/Bug Description:**
when using non default shell theme, pop shell reverts my choice of theme to system default shell theme on session start(restart or login)

**Steps to reproduce (if you know):**
Select a non default shell theme and logout or restart, pop shell will revert the theme to default

**Expected behavior:**
Shell theme should be as it was before login/restart

### PR DESCRIPTION
**Pull request by jambonmcyeah**
Combines my previous PR #269 with @scaryrawr 's PR #270

The reason for this is addressed in the comments on the comments in #270

Closes #231, Closes #230

### CODE REVIEW

File: src/search.ts [hunk 1]
```diff
@@ -29,7 +29,7 @@ export class Search {
     ) {
         this.select_cb = select;
         this.dialog = new ModalDialog({
-            styleClass: "pop-shell-search",
+            styleClass: "pop-shell-search modal-dialog",
```
Comment (isantop) [inline src/search.ts:32]: I like that we're using existing classes where they make sense here.

File: src/search.ts [hunk 2]
```diff
@@ -170,13 +182,13 @@ export class Search {
 
                 let label = new St.Label({
                     text: title,
-                    styleClass: "pop-shell-search-label",
+                    styleClass: "pop-shell-search-label list-search-result-title",
```
Comment (isantop) [inline src/search.ts:185]: Here (and the next one) also show good use of existing, supported style classes.

File: src/extension.ts [hunk 3]
```diff
@@ -1347,13 +1347,30 @@ function find_unused_workspace(): [number, any] {
...
-        let theme = Lib.dbg(Me.path + "/" + stylesheet + ".css");
-        setThemeStylesheet(theme);
-        loadTheme();
-        return theme;
+        const themeContext = St.ThemeContext.get_for_stage(global.stage);
+
+        // Get the existing shell theme if exists
+        const existingTheme = themeContext.get_theme();
+
+        // Load the pop theme style sheet
```
Comment (isantop) [inline src/extension.ts:1358]: I would prefer for this comment to read "Load the Pop Shell style sheet", as it's not really the pop theme we're loading here. This is a nitpick and not something I'd say needs to get done before merging, but it would be nice to have.

**Comment by isantop** [comment]
Pushed a copy of this branch into our repo for building/CI purposes. Please merge this PR instead of that one.

File: src/search.ts [hunk 4]
```diff
@@ -170,13 +182,13 @@ export class Search {
...
                     y_align: Clutter.ActorAlign.CENTER
                 });
 
                 label.clutter_text.set_ellipsize(Pango.EllipsizeMode.END);
 
-                let container = new widgets.Box({ styleClass: "pop-shell-search-element" })
+                let container = new widgets.Box({ styleClass: "pop-shell-search-element button" })
```
Comment (isantop) [inline src/search.ts:191]: This probably should not be a `button` class, as it makes the list of items in the Shell launcher look very strange.

Comment (jambonmcyeah) [reply src/search.ts]: Fixed

File: src/extension.ts (hunk 3 above)
Comment (jambonmcyeah) [reply src/extension.ts]: Fixed

**Comment by jambonmcyeah** [comment]
Completed all the requests

File: src/search.ts [hunk 5]
```diff
@@ -170,13 +170,13 @@ export class Search {
...
                     text: title,
-                    styleClass: "pop-shell-search-label",
+                    styleClass: "pop-shell-search-label list-search-result-title",
                     y_align: Clutter.ActorAlign.CENTER
                 });
 
                 label.clutter_text.set_ellipsize(Pango.EllipsizeMode.END);
 
-                let container = new widgets.Box({ styleClass: "pop-shell-search-element" })
+                let container = new widgets.Box({ styleClass: "pop-shell-search-element list-search-result" })
```
Comment (isantop) [inline src/search.ts:179]: This looks better in Pop and Adwaita, but in many themes it causes the text to become unreadable. I think the existing styling present for these widgets was fairly theme-agnostic and resulted in guaranteed-readable text.

**Comment by jambonmcyeah** [comment]
I addressed all your requests. While fixing the issues I noticed a bug with stylesheets only loading for the first time and fixed it. Also added detection for shell theme changes instead of relying on gtk theme changes, since they can be changed separately.

**Comment by jambonmcyeah** [comment]
There's an issue with using custom styling, which is themes that style the shell dark even on light variants such as Adwaita and Plata don't work well. I removed the `color` in the css to make them work better, however it still doesn't work great. This is why I originally set the search elements to `button` to get around this issue.

**Comment by jambonmcyeah** [comment]
The real solution to this problem is to implement search items using `St.Button` which is the [implementation by gnome-shell](https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/master/js/ui/search.js#L37), instead of detecting arrow keys manually and faking focus. A proper implementation would have mouse support and would be compatible with themes. Yet I don't have nearly enough expertise on gtk and gnome to implement this properly, so I guess we have to live with this hack for now.

**Comment by isantop** [comment]
@mmstick Some notes about the implementation of the Launcher we might consider :point_up:

**Comment by isantop** [comment]
@jambonmcyeah Can you post a screenshot of the issues you are seeing with the stock styling? I worked pretty hard to try and get the styling to be fairly theme-neutral while also looking good.

**Comment by jambonmcyeah** [comment]
Should be fixed now, I tested all the themes you mentioned and they all work fine

**Comment by isantop** [comment]
@pop-os/quality-assurance Testing branch for this is now `jambonmcyeah-shell-theme-fix`

**Comment by nicolae-stroncea** [comment]
This also fixes #227 and #216
